// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZNWvULq0EEb-NWFvdj22caf7P8hPDuQ',
    appId: '1:1030504074574:web:3686358ddc3fb700fd621f',
    messagingSenderId: '1030504074574',
    projectId: 'flutterdemo-fcf2b',
    authDomain: 'flutterdemo-fcf2b.firebaseapp.com',
    storageBucket: 'flutterdemo-fcf2b.appspot.com',
    measurementId: 'G-DWVNFSVW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzU_aoF4NlLOyujos1AH7qXhqKJOeMR-g',
    appId: '1:1030504074574:android:5f30424a6d8191f6fd621f',
    messagingSenderId: '1030504074574',
    projectId: 'flutterdemo-fcf2b',
    storageBucket: 'flutterdemo-fcf2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-WGC_mQWx2EJ7B8oXaHfLFerspUqudVI',
    appId: '1:1030504074574:ios:d74ce9f0f0cf6611fd621f',
    messagingSenderId: '1030504074574',
    projectId: 'flutterdemo-fcf2b',
    storageBucket: 'flutterdemo-fcf2b.appspot.com',
    iosClientId: '1030504074574-98v3jd2r2ipjb0seribo2ot7atumpk83.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-WGC_mQWx2EJ7B8oXaHfLFerspUqudVI',
    appId: '1:1030504074574:ios:d74ce9f0f0cf6611fd621f',
    messagingSenderId: '1030504074574',
    projectId: 'flutterdemo-fcf2b',
    storageBucket: 'flutterdemo-fcf2b.appspot.com',
    iosClientId: '1030504074574-98v3jd2r2ipjb0seribo2ot7atumpk83.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
